-- ============================================
-- SUPPLEMENTAL SEED: 2F & 3F (Self-Healing)
-- Target Database: MappedIn3DModels
-- ============================================
USE [MappedIn3DModels]
GO

-- Ensure Translation_Locations exists
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Translation_Locations]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Translation_Locations](
    [LocationId] [bigint] IDENTITY(1,1) NOT NULL,
    [MappedinId] [varchar](100) NULL,
    [LocationType] [varchar](50) NULL,
    [CategoryId] [int] NULL,
    [VN] [nvarchar](500) NULL,
    [EN] [nvarchar](500) NULL,
    [ZH] [nvarchar](500) NULL,
    [JA] [nvarchar](500) NULL,
    [KO] [nvarchar](500) NULL,
 CONSTRAINT [PK_Translation_Locations] PRIMARY KEY CLUSTERED ([LocationId] ASC)
) ON [PRIMARY]
END
GO

INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_541b67d37ddf33eb', 'room', N'Văn phòng', N'Office', N'Office', N'Office', N'Office');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b6419b9459526ab0', 'room', N'Văn phòng', N'Office', N'Office', N'Office', N'Office');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_90cbf23bf33153c5', 'room', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_2642be6775f00e8d', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_216b7975a00713e6', 'room', N'Quầy thu đổi ngoại tệ', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_121550869199e6a9', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b44b9985872568f9', 'room', N'Cửa hàng trang sức', N'Jewelry and watch store', N'Jewelry and watch store', N'Jewelry and watch store', N'Jewelry and watch store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0d96307dc8a33896', 'room', N'Cửa hàng rượu và thuốc lá', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_895bddd0cba59891', 'room', N'Trung tâm văn hóa truyền thống', N'Traditional cultural center', N'Traditional cultural center', N'Traditional cultural center', N'Traditional cultural center');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_32a654dbbb0f1b6c', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_fa6deebd1efa683a', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_1c4ddd02732445dd', 'room', N'Nhà thuốc', N'Pharmacy', N'Pharmacy', N'Pharmacy', N'Pharmacy');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0e13ebc436e64677', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_88fa42b37a404d3a', 'room', N'Cửa hàng trang sức', N'Jewelry and watch store', N'Jewelry and watch store', N'Jewelry and watch store', N'Jewelry and watch store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f8a26f40ef40fe45', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_65ddc69c144bc562', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_8125e2b351bedcd2', 'room', N'Hệ thống băng chuyền hành lý', N'Baggage Conveyor System', N'Baggage Conveyor System', N'Baggage Conveyor System', N'Baggage Conveyor System');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_002cb558a646e57e', 'room', N'Cửa hàng đồ điện tử', N'Electronics Store', N'Electronics Store', N'Electronics Store', N'Electronics Store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_94c8be89f50debeb', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_a932e5fc18a82a2f', 'room', N'Phòng cầu nguyện', N'Prayer Room', N'Prayer Room', N'Prayer Room', N'Prayer Room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_661cc9a53ed20dad', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6cee8f911c60d363', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_7259dc5439346264', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5da019cd4f11db6c', 'room', N'Khu vui chơi trẻ em', N'Kids zone', N'Kids zone', N'Kids zone', N'Kids zone');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_244a641e882bc8dc', 'room', N'Cửa hàng bán sản phẩm du lịch', N'Travel goods', N'Travel goods', N'Travel goods', N'Travel goods');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_e698f4ed04c31039', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_a739a9c3932c94fa', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_fc7b02fdacf08611', 'room', N'Phòng Internet', N'Internet Lounge', N'Internet Lounge', N'Internet Lounge', N'Internet Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f217fffdbc217890', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_cc7167316907a7d2', 'room', N'Khu vực ghế Massage - Khu cách ly', N'Massage Chair', N'Massage Chair', N'Massage Chair', N'Massage Chair');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_37cbe38c5739a5b7', 'room', N'Quầy bán món ăn địa phương', N'Local food', N'Local food', N'Local food', N'Local food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_fa64466c42ca32e1', 'room', N'Cửa hàng tiện lợi', N'convenience store', N'convenience store', N'convenience store', N'convenience store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_2615096c3de4afcf', 'room', N'Quầy cà phê', N'Coffee', N'Coffee', N'Coffee', N'Coffee');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_9ed9e3fae0e45b6c', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_edc6d85e92c6f046', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_8479a1012caf15ef', 'room', N'Cửa hàng tiện lợi', N'convenience store', N'convenience store', N'convenience store', N'convenience store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_ad7bf02bd443a36c', 'room', N'Cửa hàng bán lẻ', N'Retail', N'Retail', N'Retail', N'Retail');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_c49e458806dc7775', 'room', N'Phòng chờ ga đi quốc nội/ quốc tế', N'Dom/Int Departure Lounge', N'Dom/Int Departure Lounge', N'Dom/Int Departure Lounge', N'Dom/Int Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b7d7974e0f3ad86d', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_de3a5027f20588f9', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_660fe9be05bf5be5', 'room', N'Khu vực ghế Massage - Khu cách ly', N'Massage Chair', N'Massage Chair', N'Massage Chair', N'Massage Chair');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_7a3c7dcf79c3d0d9', 'room', N'Cửa hàng bán đồ lưu niệm', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5b4be104310203b9', 'room', N'Quầy bar thư giãn', N'Casual Bar', N'Casual Bar', N'Casual Bar', N'Casual Bar');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d62c3eecda5ffc04', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_8dff23699ff3a530', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_2d3ecc63cc8cb2a2', 'room', N'Khu nghỉ ngơi', N'Nap zone', N'Nap zone', N'Nap zone', N'Nap zone');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_c4ac6dc577169053', 'room', N'Khu vực ghế Massage - Khu cách ly', N'Massage Chair', N'Massage Chair', N'Massage Chair', N'Massage Chair');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b33a792c389d06e7', 'room', N'Phòng hút thuốc', N'Smoking room', N'Smoking room', N'Smoking room', N'Smoking room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d5d4a0c94c805fc0', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6a5aa0b67cf1f559', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_4da6f620f9948cd9', 'room', N'Quầy bán món ăn địa phương', N'Local food', N'Local food', N'Local food', N'Local food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_338931eeb30a4722', 'room', N'Cửa hàng rượu và thuốc lá', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_347582828ed810e5', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_e19454c323e24de3', 'room', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d759546c2055e5bc', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6fe2c395f06c6cc7', 'room', N'Quầy thực phẩm đóng gói', N'Package Food', N'Package Food', N'Package Food', N'Package Food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_25b60d4d538c6bd4', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d96876f038a28272', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_ad433f95b05c8ece', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_00508a6929b8584c', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5e70b889b9580d0a', 'room', N'Cửa hàng rượu và thuốc lá', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store', N'Liquor & Tobacco Store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_8d21a6bbf370272b', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0e366df3d718b553', 'room', N'Quầy thực phẩm đóng gói', N'Package Food', N'Package Food', N'Package Food', N'Package Food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_557f2f311aa020e9', 'room', N'Cửa hàng thời trang', N'Fashion shop', N'Fashion shop', N'Fashion shop', N'Fashion shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_78e17ae52c860883', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f007a1a08d0535ca', 'room', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_8f2ad2b9ab43aeaa', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_447f2e72f6b88cc7', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6d1ada40b89169f4', 'room', N'Cửa hàng bán lẻ', N'Retail', N'Retail', N'Retail', N'Retail');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_7c1139b65c34fb95', 'room', N'Ẩm thực quốc tế', N'Global Food', N'Global Food', N'Global Food', N'Global Food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_3ca59844f21e44d2', 'room', N'Khu vực ghế Massage - Khu cách ly', N'Massage Chair', N'Massage Chair', N'Massage Chair', N'Massage Chair');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_40969f9990f1ad68', 'room', N'Phòng Internet', N'Internet Lounge', N'Internet Lounge', N'Internet Lounge', N'Internet Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5dff95c90a0fdb7d', 'room', N'Khu vui chơi trẻ em', N'Kids zone', N'Kids zone', N'Kids zone', N'Kids zone');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5d7fd29cd3d14fc6', 'room', N'Cửa hàng bán đồ lưu niệm', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_93b64aa92dbff527', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_3b8df2aa433fb8c5', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_c1a6532f408cbf94', 'room', N'Phòng hút thuốc', N'Smoking room', N'Smoking room', N'Smoking room', N'Smoking room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0f4d503ba243b786', 'room', N'Ẩm thực quốc tế', N'Global Food', N'Global Food', N'Global Food', N'Global Food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f8ec30ed6aadf3a5', 'room', N'Khu vực ghế Massage - Khu cách ly', N'Massage Chair', N'Massage Chair', N'Massage Chair', N'Massage Chair');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_97f1e54fa8d57676', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0bbd1234e4e42baf', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_ee75806d088bec1e', 'room', N'Khu nghỉ ngơi', N'Nap zone', N'Nap zone', N'Nap zone', N'Nap zone');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_ec8fff416b508cc6', 'room', N'Quầy bar thư giãn', N'Casual Bar', N'Casual Bar', N'Casual Bar', N'Casual Bar');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d2c157e37cb73267', 'room', N'Cửa hàng bán lẻ', N'Retail', N'Retail', N'Retail', N'Retail');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_157104bdcda25544', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_22ccf76980e9c096', 'room', N'Quầy bán món tráng miệng', N'dessert shop', N'dessert shop', N'dessert shop', N'dessert shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5a42276b7134903a', 'room', N'Cửa hàng bán đồ lưu niệm', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop', N'Souvenir shop');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_406d856dbbffad8e', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_5fcb4b583b4773df', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_715045bebbf00f6d', 'room', N'Khu nghỉ ngơi', N'Nap zone', N'Nap zone', N'Nap zone', N'Nap zone');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_2d33af8da25b3322', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_901a3a2fbed898b5', 'room', N'Quầy bán món ăn địa phương', N'Local food', N'Local food', N'Local food', N'Local food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_0a3dfd9baffbade1', 'room', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_1b39d0ca70c1c30b', 'room', N'Cảnh quan', N'Landscape', N'Landscape', N'Landscape', N'Landscape');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_25c02f72d6070109', 'room', N'Cảnh quan', N'Landscape', N'Landscape', N'Landscape', N'Landscape');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_d0c392ebbcf494ea', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_322cb6b21c9a35f9', 'room', N'Cửa hàng đồ điện tử', N'Electronics Store', N'Electronics Store', N'Electronics Store', N'Electronics Store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f9706c268aac272e', 'room', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_32d2ebc5498e41d6', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_192e20d2f6ea6bdf', 'room', N'Cửa hàng mỹ phẩm', N'Cosmetic', N'Cosmetic', N'Cosmetic', N'Cosmetic');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_e91cefd216d0367e', 'room', N'Phòng chăm sóc em bé', N'Nursing room', N'Nursing room', N'Nursing room', N'Nursing room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6ca20f4a81d59748', 'room', N'Phòng chăm sóc em bé', N'Nursing room', N'Nursing room', N'Nursing room', N'Nursing room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_e1e6f8913efa8554', 'room', N'Phòng y tế', N'Medical Room', N'Medical Room', N'Medical Room', N'Medical Room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_71dc501287ea57df', 'room', N'Khu vực bọc hành lý', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_879105f9f6c5a78d', 'room', N'Khu vực bọc hành lý', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_233e7224b54ae05b', 'room', N'Khu vực bọc hành lý', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_50852cf314319c8e', 'room', N'Khu vực bọc hành lý', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area', N'Luggage Wrapping Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_52ab4c19f98bbe3b', 'room', N'Quầy thông tin du lịch', N'Travel Information Support)', N'Travel Information Support)', N'Travel Information Support)', N'Travel Information Support)');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b9340223de265d56', 'room', N'Quầy thông tin du lịch', N'Travel Information Support)', N'Travel Information Support)', N'Travel Information Support)', N'Travel Information Support)');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_9605235694629a21', 'room', N'Cửa hàng tiện lợi', N'convenience store', N'convenience store', N'convenience store', N'convenience store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_ee4ed4af0db2a16a', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_50badf0e3e6b9d37', 'room', N'Phòng lưu trữ hành lý', N'Luggage Storage Room', N'Luggage Storage Room', N'Luggage Storage Room', N'Luggage Storage Room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_66786e44960a0e2c', 'room', N'Quầy cà phê và bánh ngọt', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery', N'Cafe & Bakery');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f3279dd5305c92c1', 'room', N'Quầy hành lý quá khổ', N'OOG', N'OOG', N'OOG', N'OOG');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_1f44ff9349985ef4', 'room', N'Quầy thu đổi ngoại tệ', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_01e81dc1c34571df', 'room', N'Quầy bán món ăn địa phương', N'Local food', N'Local food', N'Local food', N'Local food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_62a45153a58c8135', 'room', N'Quầy đồ ăn nhanh', N'Fast food', N'Fast food', N'Fast food', N'Fast food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_10c25922c3fe91fb', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_01c95efed2c6ee6f', 'room', N'Phòng chăm sóc em bé', N'Nursing room', N'Nursing room', N'Nursing room', N'Nursing room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_69c3d6cbe47c9007', 'room', N'Văn phòng đăng ký sinh trắc học nhập cảnh', N'Biometrics Immigration Registration Office', N'Biometrics Immigration Registration Office', N'Biometrics Immigration Registration Office', N'Biometrics Immigration Registration Office');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_24f1e4bcfc8d5bf5', 'room', N'Phòng chăm sóc em bé', N'Nursing room', N'Nursing room', N'Nursing room', N'Nursing room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_c08b91061e3abfa5', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_099d60cc3b50aa38', 'room', N'Cửa hàng tiện lợi', N'convenience store', N'convenience store', N'convenience store', N'convenience store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_45a3be08e4f60e44', 'room', N'Quầy đồ ăn nhanh', N'Fast food', N'Fast food', N'Fast food', N'Fast food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_42a2ed975534d438', 'room', N'Quầy bán món ăn địa phương', N'Local food', N'Local food', N'Local food', N'Local food');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6c0174734497c57d', 'room', N'Quầy thu đổi ngoại tệ', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_7a6970b0018311d1', 'room', N'Dịch vụ bưu điện', N'Post Office', N'Post Office', N'Post Office', N'Post Office');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_f82579a05c419c56', 'room', N'Cửa hàng tiện lợi', N'convenience store', N'convenience store', N'convenience store', N'convenience store');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_13bcd0dd17458c7c', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_e8046bcc797c2314', 'room', N'Phòng lưu trữ hành lý', N'Luggage Storage Room', N'Luggage Storage Room', N'Luggage Storage Room', N'Luggage Storage Room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_761937179562c621', 'room', N'Quầy bán đồ ăn', N'Food Court', N'Food Court', N'Food Court', N'Food Court');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_b43985cfbe951628', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_7514bacb73bae49d', 'room', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_21f18fdd8b2e7b8b', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_be092a3fe77b66f8', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_a4567f70b25b1535', 'room', N'Phòng chờ hạng thương gia', N'CIP', N'CIP', N'CIP', N'CIP');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_af022a9c2e3e6eac', 'room', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_79d95c2608967e12', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_d93fdc7fce6bb5ec', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_7e74987fa960432e', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_c3a65a9b5f9b6ea0', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_425f9a88b2e6fe33', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_32e3b175c4064b0f', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_eb810bf269eecae6', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_d5b6ab6a8626d7a1', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_65555eeeb2420dfa', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_a6856f04b3553ad9', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_531ef33fa877a3b1', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_04dc7ec8e563cc1b', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_9de28e508fad9574', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_23f3bd852ed9cca5', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_51e55cf3450fe6df', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_b4bae57feeaea5a9', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_6f6ab653ef52d73c', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_8efb7d2ebfde32ad', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_b79b0a2da29def82', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_c380733e5c9f634f', 'area', N'Phòng chờ ga đi quốc nội', N'Domestic Departure Lounge', N'Domestic Departure Lounge', N'Domestic Departure Lounge', N'Domestic Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_b603c0705bcbcf54', 'area', N'Phòng chờ ga đi quốc nội', N'Domestic Departure Lounge', N'Domestic Departure Lounge', N'Domestic Departure Lounge', N'Domestic Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_94d47534dac8f29e', 'area', N'Khu ga đi nội địa', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_f7b316f41cac3eb7', 'area', N'Khu ga đi nội địa', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_609dfeae555b75ef', 'area', N'Khu ga đi nội địa', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_b6805ba02dd5abab', 'area', N'Khu ga đi nội địa', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area', N'Domestic Departure Area');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_bdc2a78ba0ff5763', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_abb132024dba2a8e', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_4cc58aed139d3212', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_3eb780e273bbdb2c', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_a683d9f4cb58c89b', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_2bdc39e0f1b44e86', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_bd4c23e8fa46d6c0', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_c13740eea220de96', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_33c86bd0e5ca64f0', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_04fefd8ffef573b2', 'area', N'Phòng chờ ga đi quốc tế', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge', N'International Departure Lounge');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_2a51ee46891780fd', 'area', N'Khu vực xuất cảnh', N'Emigration', N'Emigration', N'Emigration', N'Emigration');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('ar_91aa05a492a0714d', 'area', N'Kiểm tra an ninh/ Kiểm soát hải quan', N'Security Check/ Custom Control', N'Security Check/ Custom Control', N'Security Check/ Custom Control', N'Security Check/ Custom Control');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_6ffe2f452fd7a7c4', 'point-of-interest', N'Điểm kiểm tra an ninh soi chiếu nội địa', N'Security Checkpoint Dom', N'Security Checkpoint Dom', N'Security Checkpoint Dom', N'Security Checkpoint Dom');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('s_3fd83e4a0232f46d', 'point-of-interest', N'Điểm kiểm tra an ninh soi chiếu quốc tế', N'International Security Check', N'International Security Check', N'International Security Check', N'International Security Check');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_39744365a4936660', 'door', N'Cửa ra tàu bay - 32', N'Gate 32', N'Gate 32', N'Gate 32', N'Gate 32');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a6a7b6af8c9ecf1f', 'door', N'Cửa ra tàu bay - 27B', N'Gate 27B', N'Gate 27B', N'Gate 27B', N'Gate 27B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_894f67b3a32032b9', 'door', N'Cửa ra tàu bay - 15', N'Gate 15', N'Gate 15', N'Gate 15', N'Gate 15');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_74ca31d4531c6d6a', 'door', N'Cửa ra tàu bay - 4B', N'Gate 4B', N'Gate 4B', N'Gate 4B', N'Gate 4B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_baf60159eee92b95', 'door', N'Nhà vệ sinh', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet', N'Restroom - Toilet');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_7d4f21dee2b4fe21', 'door', N'Quầy thu đổi ngoại tệ', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange', N'Foreign Exchange');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_b670d38353d48c88', 'door', N'Khu ẩm thực cao cấp', N'Dining room', N'Dining room', N'Dining room', N'Dining room');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_49d89b9938ad1bfa', 'door', N'Cửa hàng bán lẻ', N'Retail', N'Retail', N'Retail', N'Retail');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_e681da287ebe96a3', 'door', N'Cửa ra tàu bay - 6', N'Gate 6', N'Gate 6', N'Gate 6', N'Gate 6');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_f6528c75e2c48e0e', 'door', N'Cửa ra tàu bay - 7', N'Gate 7', N'Gate 7', N'Gate 7', N'Gate 7');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_e77d795c7f628af8', 'door', N'Cửa ra tàu bay - 8B', N'Gate 8B', N'Gate 8B', N'Gate 8B', N'Gate 8B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_e961428ffac2460d', 'door', N'Cửa ra tàu bay - 9', N'Gate 9', N'Gate 9', N'Gate 9', N'Gate 9');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_41b667de73ff5f68', 'door', N'Cửa ra tàu bay - 10', N'Gate 10', N'Gate 10', N'Gate 10', N'Gate 10');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_fd2266a8940436b3', 'door', N'Cửa ra tàu bay - 12', N'Gate 12', N'Gate 12', N'Gate 12', N'Gate 12');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_75bffd60111a7856', 'door', N'Cửa ra tàu bay - 13B', N'Gate 13B', N'Gate 13B', N'Gate 13B', N'Gate 13B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_5cfad2051c807706', 'door', N'Cửa ra tàu bay - 14', N'Gate 14', N'Gate 14', N'Gate 14', N'Gate 14');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_62e13fd6e65b0b4e', 'door', N'Cửa ra tàu bay - 17', N'Gate 17', N'Gate 17', N'Gate 17', N'Gate 17');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_569030868efdaba1', 'door', N'Cửa ra tàu bay - 18', N'Gate 18', N'Gate 18', N'Gate 18', N'Gate 18');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a56ff4b0b5721dca', 'door', N'Cửa ra tàu bay - 19B', N'Gate 19B', N'Gate 19B', N'Gate 19B', N'Gate 19B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_c8994b95e6c7d155', 'door', N'Cửa ra tàu bay - 20', N'Gate 20', N'Gate 20', N'Gate 20', N'Gate 20');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a2dcd3b27cce4abe', 'door', N'Cửa ra tàu bay - 22', N'Gate 22', N'Gate 22', N'Gate 22', N'Gate 22');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_ad2a2377ee6d8fcc', 'door', N'Cửa ra tàu bay - 23', N'Gate 23', N'Gate 23', N'Gate 23', N'Gate 23');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_3a70aa8cffba5caa', 'door', N'Cửa ra tàu bay - 24B', N'Gate 24B', N'Gate 24B', N'Gate 24B', N'Gate 24B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_cffa76b459e46155', 'door', N'Cửa ra tàu bay - 25', N'Gate 25', N'Gate 25', N'Gate 25', N'Gate 25');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a361fddaf0bdc04f', 'door', N'Cửa ra tàu bay - 26', N'Gate 26', N'Gate 26', N'Gate 26', N'Gate 26');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_320595d43c403272', 'door', N'Cửa ra tàu bay - 29', N'Gate 29', N'Gate 29', N'Gate 29', N'Gate 29');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a354f045df51b29b', 'door', N'Cửa ra tàu bay - 30', N'Gate 30', N'Gate 30', N'Gate 30', N'Gate 30');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_a3739fe057dc0511', 'door', N'Cửa ra tàu bay - 31B', N'Gate 31B', N'Gate 31B', N'Gate 31B', N'Gate 31B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_fb0e081301f71004', 'door', N'Cửa ra tàu bay - 1', N'Gate 1', N'Gate 1', N'Gate 1', N'Gate 1');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_31460eb86c4d84d9', 'door', N'Cửa ra tàu bay - 2B', N'Gate 2B', N'Gate 2B', N'Gate 2B', N'Gate 2B');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_2117909396ec0190', 'door', N'Cửa ra tàu bay - 3', N'Gate 3', N'Gate 3', N'Gate 3', N'Gate 3');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_525e06d73d11d262', 'door', N'Cửa ra tàu bay - 4A', N'Gate 4A', N'Gate 4A', N'Gate 4A', N'Gate 4A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_2925f2597ff24f05', 'door', N'Cửa ra tàu bay - 2A', N'Gate 2A', N'Gate 2A', N'Gate 2A', N'Gate 2A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_796eab58fdaf1228', 'door', N'Cửa ra tàu bay - 8A', N'Gate 8A', N'Gate 8A', N'Gate 8A', N'Gate 8A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_ddb5e2820b329406', 'door', N'Cửa ra tàu bay - 13A', N'Gate 13A', N'Gate 13A', N'Gate 13A', N'Gate 13A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_aac022dd7dcec3de', 'door', N'Cửa ra tàu bay - 19A', N'Gate 19A', N'Gate 19A', N'Gate 19A', N'Gate 19A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_cacdcc070863603f', 'door', N'Cửa ra tàu bay - 24A', N'Gate 24A', N'Gate 24A', N'Gate 24A', N'Gate 24A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_5d06dca6b300b505', 'door', N'Cửa ra tàu bay - 27A', N'Gate 27A', N'Gate 27A', N'Gate 27A', N'Gate 27A');
INSERT INTO Translation_Locations (MappedinId, LocationType, VN, EN, ZH, JA, KO) VALUES ('e_aa3d5bd0cea5dc25', 'door', N'Cửa ra tàu bay - 31A', N'Gate 31A', N'Gate 31A', N'Gate 31A', N'Gate 31A');